### ISSUE TITLE
Code uses notations that will not compile on Visual Studio 2010

### ISSUE THREAD

**Issue by BurgerBob** [0x0ade/ImGuiSDL2CS#3]
Notations like :
public static void NewFrame()
            => ImGuiNative.igNewFrame();

Visual Studio 2010 is the latest visual studio that supports XNA officially.

**Comment by 0x0ade** [comment]
Visual Studio 2015 technically still supports XNA and I didn't take this into account. Thanks for telling me this! But unfortunately I don't plan on maintaining compatibility with an even more outdated compiler than the one shipping with VS 2015. (I'm already avoiding the new language features in VS 2017.)

Nevertheless, the resulting assembly still works fine. You can simply compile ImGuiXNA using any newer Visual Studio version separately and add the resulting ImGuiCS.dll and ImGuiXNA.dll as references to your project as usual:

[Debug.zip](https://github.com/0x0ade/ImGuiSDL2CS/files/1268728/Debug.zip)

**Comment by 0x0ade** [comment]
If you really require VS 2010 compatibility and want to help me out with this (because I can't tell what's supported and what's not), I'm happy to merge any pull request getting it to compile in VS 2010! I'll just not be able to verify it.

**Comment by BurgerBob** [comment]
No I think you made the right choice.

Thank you you made me find out that Microsoft now makes it easy to download
old versions of its tools (it did not use to be the case).

So if I understand well, "official" version to use XNA is now Visual 2015
with https://mxa.codeplex.com/. Maybe putting it in the Readme.me ?

Thanks

2017-08-31 19:12 GMT-04:00 Maik Macho <notifications@github.com>:

**Comment by 0x0ade** [comment]
Yup, while it's "inofficial", the [downloads provided by MXA](https://mxa.codeplex.com/releases) offer a great way to get XNA Game Studio running in Visual Studio 2015. I personally haven't had any issues with that (although I'm only developing mods, not full games). I'll put this into the README.md soon, good point
